config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'reservations#index'
  resources :reservations, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :comments, only: :create 
  end
  resources :users, only: :show
end
  #get 'reservations/index'
  #root 'reservations#index'
  #ゲストログイン機能
  #devise_for :users, controllers: {
    #registrations: 'users/registrations',
    #passwords: 'users/passwords'
  #} 
  #devise_scope :user do
    #post '/users/guest_sign_in', to: 'users/sessions#new_guest'
  #end
  #ゲストログイン機能

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :reservation

  validates :content, presence: true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :place, presence: true
  validates :introduction, presence: true 
  validates :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze
  validates :nickname, presence: true
  validates :password, format: { with: VALID_PASSWORD_REGEX }
  validates :first_name, presence: true, format: {with: /\A[ぁ-んァ-ン一-龥]/ }
  validates :family_name, presence: true,  format: {with: /\A[ぁ-んァ-ン一-龥]/ } 
  validates :first_name_kana, presence: true, format: {with: /\A[ァ-ヶー－]+\z/ } 
  validates :family_name_kana, presence: true, format: {with: /\A[ァ-ヶー－]+\z/ } 
  validates :birth_date, presence: true

  has_many :reservations
  has_many :comments
end

#ゲストログイン機能
  #def self.guest
    #find_or_create_by(email: 'guest@example.com') do |user|
      #user.password = SecureRandom.urlsafe_base64
      # user.confirmed_at = Time.now
    #end
  #end
#end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth



  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :first_name, :family_name, :first_name_kana, :family_name_kana, :birth_date])
  end
  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"] 
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to reservation_path(@comment.reservation)
    else
      @reservation = @comment.reservation
      @comments = @reservation.comments
      render "reservations/show"
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id, reservation_id: params[:reservation_id])
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :contributor_confirmation, only: [:edit, :update, :destroy]
  
  def index
    @reservations = Reservation.includes(:user)
  end

  def new
    @reservation = Reservation.new
  end

  def create
    @reservation = Reservation.new(reservation_params)
    if @reservation.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    @comment = Comment.new
    @comments = @reservation.comments
  end

  def edit
  end

  def update
    @reservation = Reservation.find(params[:id])
    if @reservation.update(reservation_params)
      redirect_to reservation_path(@reservation)
    else
      render 'edit'
    end
  end

  def destroy
    if @reservation.destroy
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  private

  def reservation_params
    params.require(:reservation).permit(:title, :place, :introduction, :image).merge(user_id: current_user.id)
  end

  def set_reservation
    @reservation = Reservation.find(params[:id])
  end

  def contributor_confirmation
    redirect_to root_path unless current_user == @reservation.user
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  before_action :check_guest, only: :create
#ゲストログイン機能
  def check_guest
    if params[:user][:email].downcase == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーの更新・削除はできません。'
    end
  end
end
#ゲストログイン機能

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :check_guest, only: %i[update destroy]
#ゲストログイン機能
  def check_guest
    if resource.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーの更新・削除はできません。'
    end
  end
end
#ゲストログイン機能

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
#ゲストログイン機能
  def new_guest
    user = User.find_or_create_by(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      # user.confirmed_at = Time.now
    end
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました'
  end
end
#ゲストログイン機能

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_devise_error_messages!
    return "" if resource.errors.empty?

    html = ""
    resource.errors.full_messages.each do |error_message|
      html += <<-EOF
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        #{error_message}
      </div>
      EOF
    end
    html.html_safe
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pavie38192</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>
          <% if user_signed_in? %>
            <div class="nav__right">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
              <%= link_to "New Proto", new_reservation_path, class: :nav__btn %>
            </div>
          <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © PROTO SPACE All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/reservations/_form.html.erb
<%# render "shared/header" %>
<%#div class="container-login"><%#application.scssにて調整%>
<%= form_with model: reservation, id: 'new_post', local: true do |f|%>
<%= render 'shared/error_messages', model: f.object %>
  <div class="field">
    <%= f.label :title, "タイトル" %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :place, "場所" %><br />
    <%= f.text_field :place %>
  </div>

  <div class="field">
    <%= f.label :introduction, "コメント" %><br />
    <%= f.text_area :introduction, class: :form__text %>
  </div>

  <div class="image-field">
    <div id="previews"></div>
    <%= f.label :image, "プロトタイプの画像" %><br />
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/reservations/_reservation.html.erb
<div class="card">
  <%= link_to image_tag(reservation.image, class: :card__img ), reservation_path(reservation) %>
  <div class="card__body">
    <%= link_to reservation.title, reservation_path(reservation), class: :card__title%>
    <p class="card__summary">
      <%= reservation.place %>
    </p>
    <%= link_to "by #{reservation.user.nickname}", user_path(reservation.user), class: :card__user %>
  </div>
</div>

app/views/reservations/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">プロトタイプ編集</h2>
      <%= render partial: "form", locals: { reservation: @reservation } %>
    </div>
  </div>
</div>

app/views/reservations/index.html.erb
<%# render "shared/header" %>
<%#div class="container-login"><%#application.scssにて調整%>
<main class="main">
  <div class="inner">
    <% if user_signed_in? %>
      <div class="greeting">
        こんにちは、
        <%= link_to "#{current_user.nickname}さん", user_path(current_user), class: :greeting__link%>
      </div>
    <% end %>
    <div class="card__wrapper">
      <%= render partial: 'reservation', collection: @reservations %>
    </div>
  </div>
</main>

app/views/reservations/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規プロトタイプ投稿</h2>
        <%= render partial: "form", locals: { reservation: @reservation } %>
    </div>
  </div>
</div>

app/views/reservations/show.html.erb
<main class="main">
  <div class="inner">
    <div class="reservation__wrapper">
      <p class="reservation__hedding">
        <%= @reservation.title %>
      </p>
      <%= link_to "by #{@reservation.user.nickname}", user_path(@reservation.user), class: :reservation__user %>
      <% if current_user == @reservation.user%>
        <div class="reservation__manage">
          <%= link_to "編集する", edit_reservation_path(@reservation), class: :reservation__btn %>
          <%= link_to "削除する", reservation_path(@reservation), method: :delete, class: :reservation__btn %>
        </div>
      <% end %>
      <div class="reservation__image">
        <%= image_tag @reservation.image %>
      </div>
      <div class="reservation__body">
        <div class="reservation__detail">
          <p class="detail__title">場所</p>
          <p class="detail__message">
            <%= @reservation.place %>
          </p>
        </div>
        <div class="reservation__detail">
          <p class="detail__title">イントロダクション</p>
          <p class="detail__message">
            <%= @reservation.introduction %>
          </p>
        </div>
      </div>
      <div class="reservation__comments">
        <% if user_signed_in? %>
          <%= form_with model: [@reservation, @comment], local: true do |f|%>
            <div class="field">
              <%= f.label :content, "コメント" %><br />
              <%= f.text_field :content, id:"comment_content" %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: :form__btn  %>
            </div>
          <% end %>
        <% end %>
        <ul class="comments_lists">
          <% @comments.each do |comment| %>
            <li class="comments_list">
              <%= comment.content%>
              <%= link_to "（#{comment.user.nickname}）", user_path(comment.user), class: :comment_user %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</main>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-expand navbar-light">
    <%= link_to "Deviseサンプル", root_path, class: 'navbar-brand' %>
    <div id="Navber">
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to 'アカウント編集', edit_user_registration_path, class: 'nav-link' %>
          </li>
          <li class="nav-item active">
            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
      <% else %>
          <li class="nav-item active">
            <%= link_to "新規登録", new_user_registration_path, class: 'nav-link' %>
          </li>
          <li class="nav-item active">
            <%= link_to "ログイン", new_user_session_path, class: 'nav-link' %>
          </li>
          <li class="nav-item active">
            <%# link_to "ゲストログイン（閲覧用）", users_guest_sign_in_path, class: 'nav-link', method: :post %>
          <li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>
  <div class='second-fotter-text-wrap'>
    <p class='second-fotter-text'>second_footer</p>
    <p class='second-fotter-text'>インスタ</p>
    <p class='second-fotter-text'>ツイッター</p>
    <p class='second-fotter-text'>Facebook</p>
  </div>
  <%# image_tag "furima-logo-color.png", class:"second-fotter-logo"%>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <h1>新規登録second_hedder</h1>
</header>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= "#{@user.nickname}さんの情報"%>
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">ニックネーム</th>
            <td class="table__col2"><%= @user.nickname %></td>
          </tr>
        </tbody>
      </table>
      <h2 class="page-heading">
        <%= "#{@user.nickname}さんの旅行記録"%>
      </h2>
      <div class="user__card">
        <%= render partial: 'reservations/reservation', collection: @user.reservations %>
      </div>
    </div>
  </div>
</div>